SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LoginsNotToSync](
	[LoginsNotToSyncID] [INT] IDENTITY(1,1) NOT NULL,
	[LoginName] [NVARCHAR](128) NOT NULL,
	[CreateDate] [DATETIMEOFFSET](7) NOT NULL,
	[LastModifiedDate] [DATETIMEOFFSET](7) NOT NULL,
 CONSTRAINT [PKC_LoginsNotToSync_LoginsNotToSyncID] PRIMARY KEY CLUSTERED 
(
	[LoginsNotToSyncID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNC_LoginsNotToSync_LoginName] UNIQUE NONCLUSTERED 
(
	[LoginName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[LoginsNotToSync] ADD  CONSTRAINT [DF_LoginsNotToSync_CreateDate]  DEFAULT (SYSDATETIMEOFFSET()) FOR [CreateDate]
GO

ALTER TABLE [dbo].[LoginsNotToSync] ADD  CONSTRAINT [DF_LoginsNotToSync_LastModifiedDate]  DEFAULT (SYSDATETIMEOFFSET()) FOR [LastModifiedDate]
GO


