SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SyncLoginsFromLinkedServerLog](
	[SyncLoginsFromLinkedServerLogID] [INT] IDENTITY(1,1) NOT NULL,
	[LogDate] [DATETIMEOFFSET](7) NOT NULL,
	[SQLToRun] [NVARCHAR](MAX) NOT NULL,
	[Description] [NVARCHAR](MAX) NOT NULL,
 CONSTRAINT [PKC_SyncLoginsFromLinkedServerLog_SyncLoginsFromLinkedServerLogID] PRIMARY KEY CLUSTERED 
(
	[SyncLoginsFromLinkedServerLogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[SyncLoginsFromLinkedServerLog] ADD  CONSTRAINT [DF_SyncLoginsFromLinkedServerLog_LogDate]  DEFAULT (SYSDATETIMEOFFSET()) FOR [LogDate]
GO


